title: ACTIVATE.HRBLOCK.COM/CRJ – H&R block activation code
description: An HR Block Activation Code is a ten-character code that came with your copy of H&R Block Tax Software when you purchased it from activate.hrblock.com/crj.
theme: jekyll-theme-Cayman
